# Generated by Django 3.2 on 2021-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../../Media/default.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
